version: "3.7"

services:
  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 1001:80
    environment:
      PMA_HOST: database
  test-app:
    depends_on:
      - database
    build:
      context: ./test-app
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: database
      MYSQL_PASSWORD: password
      MYSQL_DB: mydb
